### ISSUE TITLE
Allow both local/hosted nodes 

### ISSUE THREAD

**Issue by jennazenk** [melonproject/ipfs-frontend#134]
If there is a local node, should be the one the frontend connects over the hosted node

**Comment by schmidsi** [comment]
It doesn't seem that this is an easy task. The problem lies in the browser security model:

- If a website is requested over HTTPS everything else needs to be HTTPS as well. A possible solution could be [Content-Security-Policy](https://en.wikipedia.org/wiki/Content_Security_Policy) but we cannot use this since we are serving over IPFS so we do not have the possibility to set HTTP-headers.
- It seems that it is not easy to expose the JSON-RPC endpoints over HTTPS locally without big hacks like setting up a local nginx server that only tunnels requests from https://localhost to http://localhost.

But: If I download the frontend to my local machine, I can connect to a local parity-node. So we could instead just say: If you want to run the frontend on your on node, you need to download and run the frontend locally.

If node.js is installed, it should be as easy as: 
```bash
git clone https://github.com/melonproject/ipfs-frontend.git
cd ipfs-frontend
npm install
npm start
```

This exludes all the non-devs from running it against a local node. But I think: If one is able to install parity she should be able to install node.js and execute these commands.

Thoughts? @jennazenk @ferranbt @retotrinkler

**Comment by jennazenk** [comment]
Did you manage to run the frontend locally with a local node ? If so, I agree with you.

**Comment by schmidsi** [comment]
It is actually possible to connect to the local node with: parity --chain kovan --jsonrpc-cors https://ipfs.io/ipfs/ . It is possible to disable the "non-secure" call blocking.

But we need a better check if the node is actually up in [getParityProvider](https://github.com/melonproject/melon.js/blob/4c514c42ca7eab47e53619440c3145c88545967f/lib/utils/parity/getParityProvider.js): ```provider.isConnected``` returns always true, even if there is no node running. It throws later.

One possibility would be to call something like ```api.net.version``` inside this function which actually tries to get some value from the fund. But for this, it needs to be async.
