### ISSUE TITLE
Better indication of loading states

### ISSUE THREAD

**Issue by ddkothar** [melonproject/ipfs-frontend#165]
![image](https://user-images.githubusercontent.com/20861407/34788925-2c4ce72e-f60a-11e7-8879-65fa3ea91c4d.png)

At the time of refreshing screen. "Participation" move left, and some more minor value error.
Also, Try to reload it in new tab

After a while -- 
![image](https://user-images.githubusercontent.com/20861407/34789057-bf599422-f60a-11e7-9388-d0be694d2bf4.png)

Is it not recommended to refresh

**Comment by schmidsi** [comment]
The problem is: If you refresh the front-end gets all the data from the blockchain again, which takes some time.

We are working on some UX improvements to progressively load the data into the frontend and clearly indicate which information is still loading.

I renamed the title of this issue accordingly.
