### ISSUE TITLE
Limit orders may not be executing

### ISSUE THREAD

**Issue by modjoules** [melonproject/ipfs-frontend#231]
Limit order and market order at the same price, market order executed and the limit order did not. Also, if the limit order eventually works shouldn't the UI default to limit instead of market order type?

**Comment by jennazenk** [comment]
Hello @modjoules and thanks for taking the time to report. There is no matching algorithm on the exchange contract we are using for this version, so for you limit order to be executed, you need someone to actually take your order. 

Noted for your preference to default to limit order; I guess the reason to default to market was to make it easy for users to get their trade executed (since there is no matching algorithm).
