### ISSUE TITLE
On a buy order MLN-T are lost and the position of the other asset is not updated

### ISSUE THREAD

**Issue by pier-rosini** [melonproject/ipfs-frontend#70]
When placing a buy order the amount of MLN-T is reduced according to the order, but the amount of other asset, for instance ETH-T remains 0.

The percent column is not updated and it doesn't sum up to 100.

![melonglitch](https://user-images.githubusercontent.com/11160921/33181736-9effbf9e-d071-11e7-9eba-4f61295d5a4b.PNG)

**Comment by jennazenk** [comment]
Hello, thank your for taking the time to try out our frontend and to report your issue here. 
So indeed this is strange! I cant reproduce, so may I ask you to reproduce on your end and send me a screenshot of the holdings table (before and after) + a screenshot of the console if possible (cmd+option+J).

**Comment by pier-rosini** [comment]
Hi Jenna,
I have attached the screenshots you have requested.

As you can see, after I place my order the amount of MLN-T is deducted from
my balance, but no corresponding BTC-T is added.

Best

**Comment by jennazenk** [comment]
Can you attach a screenshot of error msg in the console ?

**Comment by jennazenk** [comment]
Did you place an order on the order book or take an order from the orderbook?

**Comment by pier-rosini** [comment]
No errors in the console, what I have sent you is the full log.

I have placed a new order.
The price I have set is such that I hit immediately an existing ask.


On 24 Nov 2017 10:10, "Jenna Zenk" <notifications@github.com> wrote:

Did you place an order on the order book or take an order from the
orderbook?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/melonproject/ipfs-frontend/issues/70#issuecomment-346778605>,
or mute the thread

**Comment by jennazenk** [comment]
Ok I see ; you placed an order on the exchange, but your order has not been taken/executed by anyone yet. So your holdings indeed don't show anymore the amount that you are trying to sell because this is held in custody in the smart contract. Once someone will take your order, you will receive the corresponding asset! This is expected behavior, however, thanks to your issue, I noticed the share price is being affected by this when it should not. We'll be fixing that shortly :) Thanks @pier-rosini for reporting issue here. Also dont forget you can directly take existing orders on the orderbook :)

**Comment by jennazenk** [comment]
We'll be working on displaying the open order and adding option to cancel them btw:  #71

**Comment by pier-rosini** [comment]
Excellent I was just about to say that.

It's a bit confusing because it seems my funds are gone, and if my orders
are pending then I should see them.

I was deceived by the fact that the total value of the fund goes down, but
as you have already pointed out, that's a bug.

As final remark, I have placed a market order and it's all good.


I have opened another ticket related to some compilation issues, it would
be great if you could give me some feedback related to that one as well.

Thanks

**Comment by jennazenk** [comment]
Sure, displaying open orders and option to cancel is in the pipeline, will notify when its on production version. 
And yes, for the fund value, that's a bug, we'll first investigate on the protocol level, add more tests on that and push new version as soon as possible :) 
Will make sure we get back on you for the other ticket :)

**Comment by pier-rosini** [comment]
Fantastic, thanks.

I believe it must be related to my local set up, but it would be great if
you could help there.




On 24 Nov 2017 11:13, "Jenna Zenk" <notifications@github.com> wrote:

Sure, displaying open orders and option to cancel is in the pipeline, will
notify when its on production version.
And yes, for the fund value, that's a bug, we'll first investigate on the
protocol level, add more tests on that and push new version as soon as
possible :)
Will make sure we get back on you for the other ticket :)

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/melonproject/ipfs-frontend/issues/70#issuecomment-346792650>,
or mute the thread
